(()=>{'use strict';
const $=id=>document.getElementById(id),C=window.CreditFile,D=window.BDC_DASHBOARD_DATA,H=window.HISTORICAL_DATA;
const esc=v=>String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const known=v=>typeof v==='number'&&Number.isFinite(v),n=v=>known(v)?v.toLocaleString('en-US',{maximumFractionDigits:0}):'Unknown',money=v=>known(v)?'$'+n(v):'Unknown',pct=v=>known(v)?(v*100).toFixed(2)+'%':'Unknown';
const titles={overview:'Overview',deal:'Deal Intel',watch:'Watchlist',bdc:'BDC Review',borrower:'Borrower Review',trends:'Trends',positions:'Positions',quality:'Data Quality & Coverage'};
const S={mode:'reviewed',date:D.meta.latestPeriod,view:'overview',sort:'',dir:1,limit:75,selected:new Set(),focus:null};let historical,tableModel=[],tableHeaders=[],tableRows=[],currentRows=[],storage=true,watch=new Set();
try{watch=new Set(JSON.parse(localStorage.getItem('portfolio-intelligence-watch-v1')||'[]'))}catch{storage=false}
function all(){if(S.mode==='reviewed')return C.rows;if(!historical)historical=H.positions.map(v=>{let r={};H.positionSchema.forEach((k,i)=>r[k]=v[i]==null?v[i]:(H.positionDictionaries[k]?.[v[i]]??v[i]));r.client=H.clients[r.clientId];r.bdc=H.bdcs[r.bdcId];return r});return historical}
function detailDateCount(){return new Set(all().map(r=>r.period)).size}function dateCoverage(){return `${detailDateCount()} dates with embedded detail / ${data().periods.length} catalog dates`}
function data(){return S.mode==='reviewed'?D:H}function key(r){return S.mode+':'+r.clientId}function groups(rs,k){const m=new Map();rs.forEach(r=>{if(!m.has(r[k]))m.set(r[k],[]);m.get(r[k]).push(r)});return [...m.values()]}
function filtered(ignoreDate=false){const q=$('search').value.toLowerCase().trim(),f=$('fund').value;return all().filter(r=>(ignoreDate||r.period===S.date)&&(!f||String(r.bdcId)===f)&&(!q||[r.client.name,...(r.client.aliases||[]),r.security,r.bdc.name].join(' ').toLowerCase().includes(q)))}
function sum(rs,k){return C.completeSum(rs,k)}function observed(rs,k){const a=rs.filter(r=>known(r[k]));return {value:a.length?a.reduce((s,r)=>s+r[k],0):null,count:a.length}}
function stats(rs){const fv=observed(rs,'fairValue');$('stats').innerHTML=[['Security rows',n(rs.length),'At selected date'],['Borrowers',n(new Set(rs.map(r=>r.clientId)).size),'Dataset identities; no new merges'],['Reporting funds',n(new Set(rs.map(r=>r.bdcId)).size),'Partial population'],['Observed fair value',money(fv.value),`${n(fv.count)} / ${n(rs.length)} rows supplied · not NAV`]].map(([a,b,c])=>`<div class="stat"><small>${a}</small><strong>${b}</strong><small>${c}</small></div>`).join('')}
function link(r){return /^https:\/\/www\.sec\.gov\//.test(r.url||'')?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">SEC filing ↗</a>`:'Unavailable'}
function borrowerButton(r){return `<button class="link" data-borrower="${r.clientId}">${esc(r.client.name)}</button>`}
function sortRows(rows,headers){const i=headers.findIndex(h=>h[0]===S.sort);if(i<0)return rows;return [...rows].sort((a,b)=>{const x=a[i]&&typeof a[i]==='object'?a[i].v:a[i],y=b[i]&&typeof b[i]==='object'?b[i].v:b[i];if(x==null)return y==null?0:1;if(y==null)return -1;return S.dir*(typeof x==='number'&&typeof y==='number'?x-y:String(x).localeCompare(String(y),undefined,{numeric:true}))})}
const cell=(v,h)=>({v,h});
function table(headers,rows,{limit=S.limit,exportable=true}={}){rows=sortRows(rows,headers);if(exportable){tableHeaders=headers;tableRows=rows;tableModel=rows.map(row=>row.map(c=>c&&typeof c==='object'?c.v:c))}return `<div class="table-scroll" tabindex="0" role="region" aria-label="${esc(titles[S.view])} data"><table><thead><tr>${headers.map(([k,label])=>`<th scope="col" aria-sort="${S.sort===k?(S.dir===1?'ascending':'descending'):'none'}"><button data-sort="${k}">${esc(label)} ${S.sort===k?(S.dir===1?'↑':'↓'):'↕'}</button></th>`).join('')}</tr></thead><tbody>${rows.slice(0,limit).map(row=>'<tr>'+row.map(c=>`<td class="${typeof (c?.v??c)==='number'?'num':''}">${c&&typeof c==='object'?c.h:esc(c)}</td>`).join('')+'</tr>').join('')}</tbody></table></div>${rows.length>limit?`<p>${n(limit)} of ${n(rows.length)} shown. CSV includes all ${n(rows.length)}.</p><button data-more>Show 100 more</button>`:''}`}
const financial=['principal','cost','fairValue','unfunded'];
function aggregateTable(rs,kind){return table([[kind,kind==='clientId'?'Borrower':'Reporting fund'],['rows','Rows'],['funds',kind==='clientId'?'Funds':'Borrowers'],...financial.map(k=>[k,{principal:'Principal',cost:'Cost',fairValue:'Complete FV',unfunded:'Unfunded'}[k]]),['observed','Observed FV'],['coverage','FV coverage']],groups(rs,kind).map(g=>{const o=observed(g,'fairValue');return [cell(kind==='clientId'?g[0].client.name:g[0].bdc.name,kind==='clientId'?borrowerButton(g[0]):`<button class="link" data-fund="${g[0].bdcId}">${esc(g[0].bdc.name)}</button>`),g.length,new Set(g.map(r=>r[kind==='clientId'?'bdcId':'clientId'])).size,...financial.map(k=>cell(sum(g,k),money(sum(g,k)))),cell(o.value,money(o.value)),`${o.count}/${g.length}`]}))}
function positionTable(rs){return table([['company','Borrower'],['fund','Fund'],['security','Security / row detail'],['principal','Principal'],['cost','Cost'],['fv','Fair value'],['unfunded','Unfunded'],['mark','FV / principal'],['costmark','FV / cost'],['rate','Rate'],['spread','Spread'],['pik','PIK'],['maturity','Maturity'],['type','Investment type'],['industry','Industry'],['lien','Lien'],['filed','Filed'],['source','Source']],rs.map(r=>[cell(r.client.name,borrowerButton(r)),r.bdc.name,cell(r.security,`<button class="link" data-row="${r.id}">${esc(r.security)}</button>`),...financial.map(k=>cell(r[k],money(r[k]))),cell(C.ratio(r,'principal'),pct(C.ratio(r,'principal'))),cell(C.ratio(r,'cost'),pct(C.ratio(r,'cost'))),...['rate','spread','pikRate'].map(k=>cell(r[k],pct(r[k]))),r.maturity,r.investmentType,r.industry,r.lien,r.filed,cell(r.url,link(r))]))}
function quantile(a,p){if(!a.length)return null;const i=(a.length-1)*p,l=Math.floor(i);return a[l]+(a[Math.ceil(i)]-a[l])*(i-l)}
function benchmark(rs){return table([['metric','Reported metric'],['n','Valid rows'],['coverage','Sample coverage'],['p25','25th percentile'],['median','Median'],['p75','75th percentile'],['range','Min → max']], [['FV / principal',r=>C.ratio(r,'principal')],['FV / cost',r=>C.ratio(r,'cost')],['Rate',r=>r.rate],['Spread',r=>r.spread],['PIK',r=>r.pikRate]].map(([name,fn])=>{const a=rs.map(fn).filter(known).sort((a,b)=>a-b);return [name,a.length,`${a.length}/${rs.length}`,cell(quantile(a,.25),pct(quantile(a,.25))),cell(quantile(a,.5),pct(quantile(a,.5))),cell(quantile(a,.75),pct(quantile(a,.75))),a.length?`${pct(a[0])} → ${pct(a.at(-1))}`:'Unknown']}))}
function maturity(rs){const buckets={'Past due date':0,'Within 12 months':0,'12–36 months':0,'Beyond 36 months':0,'Unknown / non-date':0};for(const r of rs){if(!/^\d{4}-\d{2}(-\d{2})?$/.test(r.maturity||'')){buckets['Unknown / non-date']++;continue}const months=(+r.maturity.slice(0,4)-+S.date.slice(0,4))*12+(+r.maturity.slice(5,7)-+S.date.slice(5,7));buckets[months<0?'Past due date':months<=12?'Within 12 months':months<=36?'12–36 months':'Beyond 36 months']++}return '<div class="panel"><h3>Maturity coverage</h3><p class="small">Calendar-month buckets relative to '+S.date+'. A past maturity is not a default determination.</p>'+Object.entries(buckets).map(([k,v])=>`<p>${k} <strong>${n(v)} / ${n(rs.length)}</strong><div class="bar" style="width:${rs.length?100*v/rs.length:0}%"></div></p>`).join('')+'</div>'}
function memo(rs){return `<div class="panel"><h3>Research summary · ${esc(S.date)}</h3><p>${esc(S.mode==='reviewed'?'Reviewed partial coverage':'Historical reference — not revalidated')} · ${new Set(rs.map(r=>r.clientId)).size} borrower identities · ${new Set(rs.map(r=>r.bdcId)).size} reporting funds · ${rs.length} security rows.</p><p>Complete principal ${money(sum(rs,'principal'))}; complete cost ${money(sum(rs,'cost'))}; complete FV ${money(sum(rs,'fairValue'))}; complete unfunded ${money(sum(rs,'unfunded'))}. Missing values prevent a complete total.</p><p>Observed terms are not new-issue pricing. Marks are lender valuations, not realized returns; security and currency comparability require source review.</p></div>`}
function render(){let rs=filtered();if(S.view==='watch')rs=rs.filter(r=>watch.has(key(r)));if(S.view==='borrower'&&S.selected.size)rs=rs.filter(r=>S.selected.has(r.clientId));currentRows=rs;tableHeaders=[];tableRows=[];tableModel=[];$('title').textContent=titles[S.view];$('kicker').textContent=(S.mode==='reviewed'?'REVIEWED FILINGS':'HISTORICAL REFERENCE')+' / '+S.date;$('notice').textContent=S.mode==='reviewed'?`${S.date} · Reviewed partial coverage. No full-market period established. Missing holdings are not exits or zero exposure. Source build ${D.meta.builtAt}.`:`${S.date} · Historical reference: SEC-derived retained detail, not revalidated. ${n(H.positions.length)} rows; ${dateCoverage()}; populations are incomplete. Source build ${H.meta.builtAt}. Never combined with reviewed data.`;
$('nav').innerHTML=Object.entries(titles).map(([k,v])=>`<button data-view="${k}" aria-pressed="${S.view===k}">${v}</button>`).join('');stats(rs);let html='';
if(!rs.length)html+='<p class="note">No matching rows in this evidence set, date and filter. This does not establish zero exposure or an exit. Clear filters or select another date.</p>';
if(S.view==='overview'){html+='<div class="grid"><div class="panel"><h3>Research the holdings. Preserve the evidence.</h3><p>Explore reported positions, compare lenders and inspect terms with explicit coverage. Use Deal Intel for benchmarks and Borrower Review to compare selected names.</p><p><strong>'+dateCoverage()+'</strong> in this evidence set. Historical access is available through the Evidence set selector; it is not verified history.</p></div><div class="panel"><h3>What these totals mean</h3><p>Observed FV sums only supplied values. Complete FV stays Unknown if any row is missing. Neither is fund NAV or company enterprise value.</p><p>Rates and marks describe embedded securities. No market census, credit rating or inferred borrower financials.</p></div></div><h3>Reporting fund inventory</h3>'+aggregateTable(rs,'bdcId')}
if(S.view==='deal'){html+='<p>Filtered, unweighted security-row benchmarks. Sample counts include repeated securities held by different funds, not independent deals. Narrow by fund or security search; no common tranche, currency or lien is inferred.</p>'+benchmark(rs)+maturity(rs)+memo(rs)+'<details><summary>Source-backed benchmark observations</summary>'+table([['borrower','Borrower'],['fund','Fund'],['security','Security'],['rate','Rate'],['spread','Spread'],['mark','FV / principal'],['maturity','Maturity'],['source','Source']],rs.map(r=>[r.client.name,r.bdc.name,r.security,pct(r.rate),pct(r.spread),pct(C.ratio(r,'principal')),r.maturity,cell(r.url,link(r))]),{limit:50,exportable:false})+'</details>'}
if(S.view==='watch'){html+='<p>Your browser-local list. Entries are separate by evidence set; no cross-set identity merge. '+(storage?'Saved only in this browser and website.':'Storage unavailable; session-only list.')+'</p><div class="chips">'+[...watch].filter(k=>k.startsWith(S.mode+':')).map(k=>{const id=+k.split(':')[1],c=data().clients[id];return `<button data-unwatch="${k}">Remove ${esc(c?.name||k)}</button>`}).join('')+'</div>'+aggregateTable(rs,'clientId');if(![...watch].some(k=>k.startsWith(S.mode+':')))html+='<p class="panel">Open a borrower and choose Add to watchlist to begin. A saved name with no rows on this date remains saved.</p>'}
if(S.view==='bdc'){html+='<p>Security-level fund inventory, not fund performance. Select a fund name to narrow all views. Complete totals retain missing values.</p>'+aggregateTable(rs,'bdcId');if(S.mode==='reviewed'&&$('fund').value){const scopes=[...new Set(rs.map(r=>r.scope).filter(Boolean))];html+='<h3>Reviewed scope & reconciliation</h3>'+scopes.map(s=>`<div class="panel"><p>${esc(s.coverage)}</p><p>Accession ${esc(s.accession)} · Reported net portfolio FV ${money(s.reconciliation?.reportedTotals?.fairValue==null?null:Number(s.reconciliation.reportedTotals.fairValue))}</p><p>Source-level unallocated adjustments (not assigned to borrowers): ${esc(JSON.stringify(s.reconciliation?.unallocatedAdjustments??'Unavailable'))}</p></div>`).join('')}}
if(S.view==='borrower'){const available=groups(filtered(),'clientId').sort((a,b)=>a[0].client.name.localeCompare(b[0].client.name));html+='<p>Select multiple borrowers to compare totals side by side. Search narrows the selection menu. Identities and aliases are retained as supplied, with no new name merges.</p><label>Add borrower to comparison <select id="addBorrower"><option value="">Choose a borrower…</option>'+available.map(g=>`<option value="${g[0].clientId}">${esc(g[0].client.name)}</option>`).join('')+'</select></label><div class="chips">'+[...S.selected].map(id=>`<button data-remove="${id}">${esc(data().clients[id].name)} ×</button>`).join('')+(S.selected.size?'<button id="clearSelection">Clear comparison</button>':'')+'</div>'+aggregateTable(rs,'clientId')+memo(rs);if(S.focus!==null){const name=data().clients[S.focus]?.name;html+=`<div class="panel"><h3>${esc(name)}</h3><button id="toggleWatch">${watch.has(S.mode+':'+S.focus)?'Remove from':'Add to'} watchlist</button><p>${S.mode==='reviewed'?'Reviewed lender evidence below retains the exact source-row comparison engine.':'Historical reference only: source observations below; exact-row changes are not asserted.'}</p></div>`;if(S.mode==='history')html+=positionTable(filtered().filter(r=>r.clientId===S.focus))}}
if(S.view==='positions'){html+='<p>All matching rows are exported. Select a security for every supplied field and provenance; select a borrower for lender evidence. Sort any column; Unknown sorts last.</p>'+positionTable(rs)}
if(S.view==='trends'){const time=filtered(true),by=groups(time,'period').sort((a,b)=>a[0].period.localeCompare(b[0].period));html+='<p class="note">Coverage over time, not a performance series. Date selector controls the cards; the table spans all available dates with the same fund/search filters. Do not infer returns, entries or exits from changing populations.</p>'+table([['date','Reporting date'],['rows','Rows'],['funds','Funds'],['borrowers','Borrowers'],['fv','Observed FV'],['coverage','FV coverage'],['match','Eligible reviewed row matches']],by.map(g=>{const o=observed(g,'fairValue');return [cell(g[0].period,`<button class="link" data-date="${g[0].period}">${g[0].period}</button>`),g.length,new Set(g.map(r=>r.bdcId)).size,new Set(g.map(r=>r.clientId)).size,cell(o.value,money(o.value)),`${o.count}/${g.length}`,S.mode==='reviewed'?g.filter(r=>C.matchPrior(r).row).length:'Not validated']}));html+='<div class="panel"><h3>Comparable changes</h3><p>Reviewed Borrower Review shows exact-row changes only for unique unchanged security terms, stable accepted scope and eligible adjacent quarter. Matching does not prove tranche identity. Historical reference has no approved change engine.</p><p>Reference dates overlapping reviewed dates: '+H.periods.filter(p=>D.periods.includes(p)).join(', ')+'. These are separate alternate observations, never summed together. No cross-set row identity or additive universe is claimed.</p></div>'}
if(S.view==='quality'){html+='<p>Selected-date field completeness. Flags and classifications are raw supplied fields, not verified negatives. Historical proxies are never promoted to credit facts.</p>'+table([['field','Field'],['present','Supplied rows'],['missing','Unknown rows'],['coverage','Coverage']],['principal','cost','fairValue','unfunded','rate','spread','pikRate','maturity','industry','lien','investmentType','fairValueLevel','url','acquisitionDate','geography'].map(k=>{const count=rs.filter(r=>r[k]!=null&&r[k]!=='').length;return [k,count,rs.length-count,cell(rs.length?count/rs.length:null,rs.length?pct(count/rs.length):'Unknown')]}))+'<div class="grid"><div class="panel"><h3>Reviewed boundary</h3><p>'+n(D.positions.length)+' retained rows · '+D.periods.join(', ')+'. Accepted subset, not a full market. Reviewed numeric data and matching engine are retained without changes.</p><p>Source: reviewed direct SEC filings. Exact source links, accession and row detail are under Positions.</p></div><div class="panel"><h3>Historical boundary</h3><p>'+n(H.positions.length)+' embedded reference rows · '+H.detailPeriodCount+' dates with embedded detail / '+H.periods.length+' catalog dates. Catalog dates without retained detail show an empty state. Source: '+esc(H.meta.source)+'. Build '+esc(H.meta.builtAt)+'. Broader archive metadata is not the embedded detail count.</p><p>Legacy precomputed totals, risk and performance claims excluded. Names, terms and source fields remain as supplied, without revalidation. Overlapping dates never contribute to reviewed totals.</p></div></div><div class="panel"><h3>Unavailable or not established</h3><p>Full-market census; complete extraction; currency comparability; revenue, EBITDA, leverage, liquidity, covenant compliance; definitive non-accrual or security identity. Missing attributes cannot be recovered by adding a view.</p></div>'}
$('view').innerHTML=html;$('evidence').hidden=!(S.view==='borrower'&&S.focus!==null&&S.mode==='reviewed');$('tablecsv').disabled=!tableHeaders.length;
if($('addBorrower'))$('addBorrower').onchange=e=>{if(e.target.value!==''){S.selected.add(+e.target.value);render()}};if($('clearSelection'))$('clearSelection').onclick=()=>{S.selected.clear();render()};if($('toggleWatch'))$('toggleWatch').onclick=()=>{const k=S.mode+':'+S.focus;watch.has(k)?watch.delete(k):watch.add(k);saveWatch();render()};
}
function saveWatch(){try{localStorage.setItem('portfolio-intelligence-watch-v1',JSON.stringify([...watch]));storage=true}catch{storage=false}}
function setOptions(){const d=data();$('date').innerHTML=d.periods.slice().sort().reverse().map(p=>`<option>${p}</option>`).join('');if(!d.periods.includes(S.date))S.date=d.periods.includes('2026-03-31')?'2026-03-31':d.periods.at(-1);$('date').value=S.date;$('fund').innerHTML='<option value="">All reporting funds</option>'+d.bdcs.map((b,i)=>`<option value="${i}">${esc(b.name)}</option>`).join('')}
function selectBorrower(id){S.focus=+id;S.view='borrower';render();if(S.mode==='reviewed'){const b=document.createElement('button');b.dataset.company=id;b.hidden=true;document.body.append(b);b.click();b.remove();$('engineScaffold').hidden=true;document.querySelectorAll('#profile details').forEach(e=>e.open=true);$('evidence').hidden=false}}
function sourceDetail(id){const r=all().find(r=>String(r.id)===id&&r.period===S.date);if(!r)return;const p=document.createElement('section');p.className='panel';p.id='sourceDetail';p.innerHTML='<h3>Source observation · '+esc(r.client.name)+'</h3><p>'+esc(S.mode==='reviewed'?'Reviewed accepted row':'Historical reference — not revalidated')+' · '+esc(r.period)+' · '+link(r)+'</p><button id="closeDetail">Close detail</button><dl class="source-grid">'+data().positionSchema.map(k=>'<dt>'+esc(k)+'</dt><dd>'+esc(r[k]!=null&&typeof r[k]==='object'?JSON.stringify(r[k]):r[k])+'</dd>').join('')+'</dl>';$('sourceDetail')?.remove();$('view').prepend(p);$('closeDetail').onclick=()=>p.remove();p.scrollIntoView({block:'start'})}
function csvText(){if(S.mode==='reviewed')return C.csv(currentRows);const keys=H.positionSchema;return [['evidenceStatus','company','fund',...keys],...currentRows.map(r=>['Historical reference — not revalidated',r.client.name,r.bdc.name,...keys.map(k=>r[k]!=null&&typeof r[k]==='object'?JSON.stringify(r[k]):r[k])])].map(row=>row.map(C.csvCell).join(',')).join('\r\n')}
function tableText(){return [['evidenceStatus','reportingDate',...tableHeaders.map(h=>h[1])],...tableModel.map(r=>[S.mode==='reviewed'?'Reviewed partial coverage':'Historical reference — not revalidated',S.view==='trends'?'Multiple dates':S.date,...r])].map(r=>r.map(C.csvCell).join(',')).join('\r\n')}
function download(text,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('csv').onclick=()=>download(csvText(),S.mode+'-'+S.view+'-'+S.date+'-positions.csv');$('tablecsv').onclick=()=>download(tableText(),S.mode+'-'+S.view+'-'+S.date+'-analysis.csv');
let printLimit;window.addEventListener('beforeprint',()=>{printLimit=S.limit;S.limit=Math.max(S.limit,tableModel.length);render();document.querySelectorAll('#view details,#profile details').forEach(x=>x.open=true)});window.addEventListener('afterprint',()=>{S.limit=printLimit||75;render()});$('print').onclick=()=>window.print();
$('date').onchange=()=>{S.date=$('date').value;S.limit=75;if(S.mode==='reviewed'){$('periodSelect').value=S.date;$('periodSelect').dispatchEvent(new Event('change'))}render()};
$('mode').onchange=async()=>{const next=$('mode').value;if(next==='history'){try{await window.loadHistory()}catch(e){$('mode').value=S.mode;return}}S.mode=next;S.focus=null;S.selected.clear();S.sort='';S.limit=75;setOptions();if(S.mode==='reviewed'){$('periodSelect').value=S.date;$('periodSelect').dispatchEvent(new Event('change'))}render()};$('fund').onchange=()=>{S.limit=75;render()};let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{S.limit=75;render()},120)};$('reset').onclick=()=>{$('search').value='';$('fund').value='';S.selected.clear();S.focus=null;render()};
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){S.view=t.dataset.view;S.sort='';S.limit=75;render()}if(t.dataset.sort){S.dir=S.sort===t.dataset.sort?-S.dir:1;S.sort=t.dataset.sort;render()}if(t.hasAttribute('data-more')){S.limit+=100;render()}if(t.dataset.borrower)selectBorrower(t.dataset.borrower);if(t.dataset.fund){$('fund').value=t.dataset.fund;S.view='bdc';render()}if(t.dataset.remove){S.selected.delete(+t.dataset.remove);render()}if(t.dataset.unwatch){watch.delete(t.dataset.unwatch);saveWatch();render()}if(t.dataset.row)sourceDetail(t.dataset.row);if(t.dataset.date){$('date').value=t.dataset.date;$('date').dispatchEvent(new Event('change'))}if(t.id==='watchButton'){const k='reviewed:'+C.state.selected;const engineWatch=JSON.parse(localStorage.getItem('sec-bdc-credit-watchlist-v1')||'[]');engineWatch.includes(D.clients[C.state.selected].key)?watch.add(k):watch.delete(k);saveWatch()}});
// Reuse the reviewed engine's actual profile renderer inside the unified research section.
$('profileMount').append($('profile'));setOptions();render();window.Unified={state:S,filtered,all,render,csvText,tableText,get table(){return tableModel},get currentRows(){return currentRows},benchmark,selectBorrower};window.UNIFIED_READY=true;
})();
