(function(){
'use strict';
const raw=window.BDC_DASHBOARD_DATA;
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const known=v=>typeof v==='number'&&Number.isFinite(v), norm=v=>String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const pct=v=>known(v)?(v*100).toFixed(2)+'%':'Unknown';
const money=v=>known(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v):'Unknown';
const short=v=>known(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(v):'Unknown';
const pp=v=>known(v)?(v>0?'+':'')+(v*100).toFixed(2)+' pp':'Unavailable';
const ratio=(r,k)=>known(r.fairValue)&&known(r[k])&&r[k]>0?r.fairValue/r[k]:null;
const scopes=new Map((raw.meta.directAcceptance||[]).map(s=>[s.period+'|'+s.accession,s]));
const rows=raw.positions.map(values=>{const r={};raw.positionSchema.forEach((k,i)=>{const v=values[i];r[k]=v==null?v:(raw.positionDictionaries?.[k]?.[v]??v)});r.client=raw.clients[r.clientId];r.bdc=raw.bdcs[r.bdcId];r.scope=scopes.get(r.period+'|'+r.adsh);return r;});
const byCompany=new Map();rows.forEach(r=>{if(!byCompany.has(r.clientId))byCompany.set(r.clientId,[]);byCompany.get(r.clientId).push(r)});
const companies=raw.clients.map((c,id)=>({...c,id,search:norm([c.name,...(c.aliases||[])].join(' '))}));
const url=new URL(location.href), requested=url.searchParams.get('period');
const state={period:requested||raw.meta.latestPeriod,selected:null,query:'',limit:60,watchOnly:false,multiOnly:false,currentOnly:true,sort:'lenders',fund:'0'};
const requestedCompany=url.searchParams.get('company')||url.searchParams.get('clients');
if(requestedCompany)state.selected=companies.find(c=>c.key===requestedCompany)?.id??null;
let watch=new Set(),storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem('sec-bdc-credit-watchlist-v1')||'[]');if(Array.isArray(saved))watch=new Set(saved.filter(k=>typeof k==='string'));}catch{storageAvailable=false}
function storageNote(){ $('storageNote').textContent=storageAvailable?'Watchlist stays in this browser. No client affiliations assumed.':'Browser storage unavailable. Watchlist lasts only for this open page.'; }
function updateURL(){const u=new URL(location.href);u.searchParams.set('period',state.period);u.searchParams.delete('clients');if(state.selected!==null)u.searchParams.set('company',companies[state.selected].key);else u.searchParams.delete('company');try{history.replaceState(null,'',u)}catch{}}
function current(id=state.selected){return(byCompany.get(id)||[]).filter(r=>r.period===state.period)}
function previousPeriod(period=state.period){
 // Compare consecutive quarter ends on this reporting cadence, never another fund's intervening date.
 const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(period);if(!m)return;
 const y=Number(m[1]),month=Number(m[2]),day=Number(m[3]);
 if(month<1||month>12||day!==new Date(Date.UTC(y,month,0)).getUTCDate())return;
 return new Date(Date.UTC(y,month-3,0)).toISOString().slice(0,10);
}
function completeSum(rs,k){return rs.length&&rs.every(r=>known(r[k]))?rs.reduce((a,r)=>a+r[k],0):null}
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='www.sec.gov'?u.href:null}catch{return null}}
function source(r,label='SEC filing'){const u=safeURL(r.url||r.sources?.source);return u?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'Source link unavailable'}
function sourceInfo(r){return `<div class="source-row" id="source-${r.id}"><strong>${esc(r.bdc.name)}</strong> · Row ${r.id}<p>${esc(r.security||'Security description unknown')}</p><p class="small">Reported ${esc(r.reportPeriod||r.period)} · Filed ${esc(r.filed||'unknown')} · Maturity ${esc(r.maturity||'unknown')} · ${source(r)}</p><p class="small">${esc(r.scope?.coverage||'Accepted scope unavailable')}<br>Accession ${esc(r.adsh)} · ${r.rawRows??'Unknown'} underlying row(s)</p></div>`}
// Exact source attributes form viewing buckets, never asserted tranche identifiers.
function termsKey(r){return JSON.stringify([norm(r.investmentType),r.maturity??null,r.spread??null,r.pikRate??null,norm(r.variableRateType),norm(r.lien)]);}
function groups(rs){const m=new Map();for(const r of rs){const k=termsKey(r);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return [...m.values()].sort((a,b)=>new Set(b.map(r=>r.bdcId)).size-new Set(a.map(r=>r.bdcId)).size);}
// A unique unchanged source security with stable reported maturity/spread, same CIK
// and identical accepted scope is eligible for observed-row change (not tranche proof).
function identity(r){if(!r.scope||!r.security||!r.maturity||!known(r.spread))return null;return JSON.stringify([r.scope.cik,r.scope.coverage,r.client.key,r.security,r.maturity,r.spread,r.pikRate,r.investmentType,r.lien,r.variableRateType,r.acquisitionDate]);}
function matchPrior(r){const prior=previousPeriod(r.period);if(!prior)return{row:null,reason:'No earlier accepted quarter'};const key=identity(r);if(!key)return{row:null,reason:'Missing security, maturity, spread or accepted scope'};const all=byCompany.get(r.clientId)||[];const before=all.filter(p=>p.period===prior&&identity(p)===key),now=all.filter(p=>p.period===r.period&&identity(p)===key);return before.length===1&&now.length===1?{row:before[0],reason:'Unique exact reported-row match; not confirmed tranche identity'}:{row:null,reason:'No unique unchanged row in compatible accepted scope'};}
function nearMaturity(r){if(!/^\d{4}-\d{2}(-\d{2})?$/.test(r.maturity||''))return false;const p=new Date(state.period+'T00:00:00Z');p.setUTCFullYear(p.getUTCFullYear()+1);return r.maturity.slice(0,7)<=p.toISOString().slice(0,7);}
function signals(rs){return{discount:rs.filter(r=>{const v=ratio(r,'cost');return known(v)&&v<.9}).length,pik:rs.filter(r=>known(r.pikRate)&&r.pikRate>0).length,maturity:rs.filter(nearMaturity).length};}
function coverage(){
  // Count distinct funds in accepted rows, not the non-exhaustive tracked reference.
  const counts=new Map();
  for(const r of rows){
    if(!counts.has(r.period))counts.set(r.period,new Set());
    counts.get(r.period).add(r.scope?.cik||r.bdcId);
  }
  const quarters=[...counts].sort(([a],[b])=>a.localeCompare(b)).map(([period,funds])=>`${period.slice(0,4)} Q${Math.ceil(Number(period.slice(5,7))/3)} (${period}): ${funds.size} funds`).join('; ');
  $('coverageBanner').textContent=`${state.period} · Partial reviewed coverage: ${counts.get(state.period)?.size||0} funds. ${quarters ? quarters+'. ' : ''}Not exhaustive active-market coverage. No filing or no accepted rows is not an exit or zero exposure.`;
}
function renderResults(){const tokens=norm(state.query).split(' ').filter(Boolean);let cs=companies.filter(c=>tokens.every(t=>c.search.includes(t))&&(!state.watchOnly||watch.has(c.key)));const counts=new Map(cs.map(c=>[c.id,new Set(current(c.id).map(r=>r.bdcId)).size]));if(state.currentOnly)cs=cs.filter(c=>counts.get(c.id)>0);if(state.multiOnly)cs=cs.filter(c=>counts.get(c.id)>1);cs.sort((a,b)=>(state.sort==='lenders'?(counts.get(b.id)-counts.get(a.id)):0)||a.name.localeCompare(b.name));$('resultCount').textContent=`${cs.length.toLocaleString()} companies${state.query?' matching search':''} · ${esc(state.period)}${state.currentOnly?' · current rows only':' · including historical companies'}`;$('companyResults').innerHTML=cs.slice(0,state.limit).map(c=>`<button class="result ${c.id===state.selected?'selected':''}" data-company="${c.id}" aria-pressed="${c.id===state.selected}"><strong>${watch.has(c.key)?'★ ':''}${esc(c.name)}</strong><span>${counts.get(c.id)} reporting lender${counts.get(c.id)===1?'':'s'}${!counts.get(c.id)?' · no rows on '+esc(state.period)+' · last accepted '+esc((byCompany.get(c.id)||[]).map(r=>r.period).sort().pop()||'unknown'):''}</span></button>`).join('')||'<p>No matching companies. Try a shorter name or clear current-date / watchlist / multiple-lender filters.</p>';$('moreResults').hidden=cs.length<=state.limit;}
function selectCompany(id,focus=false){state.selected=Number(id);updateURL();renderResults();renderProfile();if(focus){$('profile').focus({preventScroll:true});$('profile').scrollIntoView({block:'start'});}}
function rowMarkup(r){const m=matchPrior(r),p=m.row,now=ratio(r,'principal'),before=p?ratio(p,'principal'):null;return `<tr id="mark-row-${r.id}" tabindex="-1" data-movement="${movement(r)}"><td class="lender"><strong>${esc(r.bdc.name)}</strong><small>${source(r)} · filed ${esc(r.filed||'unknown')}<br>Row ${r.id} · ${esc(r.period)}</small></td><td class="num"><span class="mark ${known(now)&&now<.9?'negative':''}">${pct(now)}</span><small><br>FV / principal</small></td><td class="num">${pct(ratio(r,'cost'))}<small><br>FV / cost</small></td><td class="num">${money(r.principal)}<br><small>Cost ${money(r.cost)}</small></td><td class="num">${money(r.fairValue)}<br><small>Unfunded ${money(r.unfunded)}</small></td><td class="num">${pct(r.rate)}<br><small>PIK ${pct(r.pikRate)}</small></td><td><span class="nowrap">${p?pct(before):'Unavailable'}</span><small><br>${p?source(p,'Prior filing'):esc(m.reason)}<br>${p?'Observed-row match':''}</small></td><td class="num ${known(now)&&known(before)&&now<before?'negative':''}">${known(now)&&known(before)?pp(now-before):'Unavailable'}</td></tr>`;}
function renderGroup(rs,i){const r=rs[0],lenders=new Set(rs.map(r=>r.bdcId)).size,marks=rs.map(r=>ratio(r,'principal')).filter(known),range=marks.length>1?pp(Math.max(...marks)-Math.min(...marks)):null;return `<section class="group"><div class="group-head"><span class="eyebrow">REPORTED-TERM GROUP ${String(i+1).padStart(2,'0')} / ${lenders} LENDER${lenders===1?'':'S'}</span><h3>${esc(r.investmentType||'Instrument type not captured')}</h3><p>Maturity ${esc(r.maturity||'unknown')} · Spread ${pct(r.spread)} · PIK ${pct(r.pikRate)} · Lien ${esc(r.lien||'not captured')}</p><p class="small">Comparability uncertain: tranche and currency identity unverified${!r.investmentType||!r.lien?'; key attributes missing':''}.${range&&lenders>1?` Observed FV/principal range: ${range}; includes within-lender variation; not confirmed lender disagreement.`:''}</p></div><p class="scroll-hint small">Scroll table horizontally for prior marks and quarter changes.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Lender comparison group ${i+1}"><table><thead><tr><th scope="col">Lender / source</th><th scope="col">FV / principal (%)</th><th scope="col">FV / cost (%)</th><th scope="col">Principal / cost ($)</th><th scope="col">Fair value ($)</th><th scope="col">Rate / PIK</th><th scope="col">Prior FV / principal</th><th scope="col">Change (pp)</th></tr></thead><tbody>${rs.map(rowMarkup).join('')}</tbody></table></div><details class="source-details"><summary>Instrument descriptions & source evidence (${rs.length} rows)</summary>${rs.map(sourceInfo).join('')}</details></section>`;}
function aggregateChange(rs,previous){const m=new Map();for(const r of [...rs,...previous]){if(!r.scope)continue;const k=r.scope.cik+'|'+r.scope.coverage;if(!m.has(k))m.set(k,{now:[],before:[]});m.get(k)[r.period===state.period?'now':'before'].push(r)}let now=0,before=0,count=0;const omitted=[];for(const v of m.values()){const n=completeSum(v.now,'fairValue'),p=completeSum(v.before,'fairValue');if(n===null||p===null){omitted.push((v.now[0]||v.before[0]).bdc.name);continue}now+=n;before+=p;count++}return{now,before,count,omitted:[...new Set(omitted)]};}
function historyMarkup(rs){const prior=previousPeriod(),all=byCompany.get(state.selected)||[],previous=all.filter(r=>r.period===prior),a=aggregateChange(rs,previous),matches=rs.filter(r=>matchPrior(r).row);return `<section class="history" id="historySection"><span class="eyebrow">03 / CHANGES OVER TIME</span><h2>${esc(prior||'No prior accepted quarter')} → ${esc(state.period)}</h2><p><strong>${matches.length} of ${rs.length} current rows have unique unchanged source-row matches.</strong> Current/prior marks appear above only for those rows; unknown or zero denominators never produce a ratio.</p><p>${a.count?`Compatible-scope reported FV: <strong>${short(a.before)} → ${short(a.now)}</strong> (${money(a.now-a.before)}), across ${a.count} contributing filer(s).`:'Aggregate change unavailable: requires compatible accepted scopes and complete FV in both quarters.'}</p><p class="small">This is observed fair-value change, not investment return, purchases, sales or operating performance. All selected company rows within a contributing filer must have reported FV; reported zero counts. Missing-quarter or incomplete/incompatible scopes excluded${a.omitted.length?': '+esc(a.omitted.join('; ')):'.'}</p><details><summary>Browse raw accepted history (${all.length} rows)</summary><p class="small">Unmatched rows remain visible, not classified as entries or exits. Export all quarters for full numeric detail.</p>${all.map(r=>`<div class="source-row"><strong>${esc(r.period)} · ${esc(r.bdc.name)}</strong><p>${esc(r.security)}</p><p>FV ${money(r.fairValue)} · Principal ${money(r.principal)} · FV/principal ${pct(ratio(r,'principal'))} · FV/cost ${pct(ratio(r,'cost'))} · ${source(r)}</p></div>`).join('')}</details></section>`;}
function movement(r){const p=matchPrior(r).row,n=ratio(r,'principal'),b=p?ratio(p,'principal'):null;return !known(n)||!known(b)?'unavailable':n<b?'decreased':n>b?'increased':'unchanged';}
function evidenceSummary(rs){
 const prior=previousPeriod(),matched=rs.filter(r=>matchPrior(r).row).length,valid=rs.filter(r=>movement(r)!=='unavailable').length;
 return `<section class="evidence-summary" aria-labelledby="evidenceHeading"><h3 id="evidenceHeading">What changed in reported marks?</h3><p>${esc(prior||'No earlier accepted date')} → ${esc(state.period)} · FV / principal only</p><dl>${['decreased','increased','unchanged','unavailable'].map(k=>{const count=rs.filter(r=>movement(r)===k).length;return `<div><dt>${k==='unavailable'?'Change unavailable':'Mark '+k}</dt><dd>${count?`<button data-jump-movement="${k}">${count} rows</button>`:'0 rows'}</dd></div>`}).join('')}</dl><p class="small">${valid} / ${rs.length} rows have valid marks on both dates; ${matched} / ${rs.length} have unique source-row matches. Observations, not returns or credit ratings.</p><details><summary>Matching limits &amp; descriptive indicators</summary><p class="small">Same FV/principal basis and positive denominators on both dates. Direction uses unrounded ratios; displayed percentage-point changes are rounded. Missing values are unavailable, never unchanged. Exact-row matching requires stable security, maturity, spread and accepted scope; fixed-rate rows without spread may be excluded. A match does not prove tranche identity. <a href="#historySection">Review scope exclusions</a>.</p><div class="signals">${(()=>{const s=signals(rs);return `<span class="badge">${s.discount} debt/equity rows below 90% FV/cost</span><span class="badge">${s.pik} rows with reported PIK</span><span class="badge">${s.maturity} rows due / within 12 months</span>`})()}</div><p class="small">Discounts do not establish default or non-accrual; PIK may be contractual. Operating results and covenant compliance are not supplied.</p></details></section>`;
}
function renderProfile(){if(state.selected===null){$('profile').innerHTML=`<div class="empty"><span class="eyebrow">BORROWER FIRST / LENDER EVIDENCE</span><h2>Know the company.<br>Compare the marks.</h2><p>Search a company to inspect what its reporting lenders hold, where valuations differ, and what changed between filings.</p><p class="small">Start with a multi-lender example — these are research examples, not your clients.</p><div class="example-row">${['Medallia, Inc.','Pluralsight, LLC','IRI Group Holdings, Inc.'].map(name=>{const c=companies.find(c=>c.name===name)||companies.find(c=>c.name.toLowerCase().includes(name.split(',')[0].toLowerCase()));return c?`<button data-company="${c.id}">${esc(c.name)}</button>`:''}).join('')}</div><p class="note">The accepted filings describe lender valuations and security terms. Revenue, EBITDA, leverage, liquidity and covenant compliance are not supplied here.</p></div>`;return}
const c=companies[state.selected],rs=current(),s=signals(rs),fv=completeSum(rs,'fairValue'),lenders=new Set(rs.map(r=>r.bdcId)).size;
$('profile').innerHTML=`<div class="profile-head"><div><span class="eyebrow">02 / COMPANY CREDIT PROFILE</span><h2>${esc(c.name)}</h2><p class="small">${esc(state.period)} · ${esc((c.industries||[]).join(' / ')||'Industry not captured')}<br>Names in accepted data: ${esc((c.aliases||[]).join('; '))}</p></div><button id="watchButton" aria-pressed="${watch.has(c.key)}">${watch.has(c.key)?'Remove from watchlist':'+ Watchlist'}</button></div><div class="actions"><button id="backToSearch">Find another company</button><a href="#comparison">Lender comparison</a><a href="#historySection">Changes over time</a><button id="exportCompany">Export quarter CSV</button><button id="exportHistory">Export all quarters CSV</button></div>${evidenceSummary(rs)}<details class="holding-context"><summary>Holdings context · ${lenders} lenders · ${rs.length} rows</summary><div class="fact-strip"><div><strong>${lenders}</strong><span>Reporting lenders · selected quarter</span></div><div><strong>${rs.length}</strong><span>Accepted security rows</span></div><div><strong>${short(fv)}</strong><span>${fv===null?'Total FV unknown / incomplete':'Reported company FV · not enterprise value'}</span></div></div></details>${!rs.length?'<p class="note">No accepted rows for this company in the selected quarter. This is not evidence of an exit or zero exposure.</p>':''}<div class="section-head" id="comparison"><div><span class="eyebrow">SIDE-BY-SIDE / RETAINING INSTRUMENT DIFFERENCES</span><h2>Lender comparison</h2></div></div><p class="small">FV/principal measures the reported principal mark; FV/cost measures the cost mark. They are not interchangeable. Unknown means not reported/captured; 0 is reported zero. Dollar values are as supplied in the accepted dataset; currency comparability is not established.</p>${groups(rs).map(renderGroup).join('')}${historyMarkup(rs)}`;
$('backToSearch').onclick=()=>{$('queryInput').focus();$('queryInput').scrollIntoView({block:'center'});};
$('watchButton').onclick=()=>{if(watch.has(c.key))watch.delete(c.key);else watch.add(c.key);try{localStorage.setItem('sec-bdc-credit-watchlist-v1',JSON.stringify([...watch]));if(localStorage.getItem('sec-bdc-credit-watchlist-v1')!==JSON.stringify([...watch]))throw Error();storageAvailable=true}catch{storageAvailable=false}storageNote();renderResults();renderProfile();$('watchButton').focus({preventScroll:true})};$('exportCompany').onclick=()=>download(rs,'company-'+state.period);$('exportHistory').onclick=()=>download(byCompany.get(state.selected)||[],'company-all-quarters');}
const csvColumns=['company','lender','period','filed','security','investmentType','lien','maturity','principal','cost','fairValue','unfunded','fvPrincipal','fvCost','rate','spread','pikRate','priorPeriod','priorFVPrincipal','changePP','matchStatus','comparability','nonAccrual','source','priorSource','acceptedScope','rowId'];
function csvCell(v){let s=v===null||v===undefined?'Unknown':String(v);if(/^[=+@\t\r]/.test(s)||(/^\s*-/.test(s)&&typeof v!=='number'))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function exportValues(r){const m=r.period===state.period?matchPrior(r):{row:null,reason:'Historical row; select its quarter for comparison'},p=m.row,n=ratio(r,'principal'),b=p?ratio(p,'principal'):null;return [r.client.name,r.bdc.name,r.period,r.filed,r.security,r.investmentType,r.lien,r.maturity,r.principal,r.cost,r.fairValue,r.unfunded,n,ratio(r,'cost'),r.rate,r.spread,r.pikRate,p?.period,p?b:null,known(n)&&known(b)?(n-b)*100:null,m.reason,'Uncertain: reported terms do not prove tranche or currency identity','Not established; discounts not used',r.url,p?.url,r.scope?.coverage,r.id]}
function csv(rs){return [csvColumns.map(csvCell).join(','),...rs.map(r=>exportValues(r).map(csvCell).join(','))].join('\r\n')}
function download(rs,name){const blob=new Blob(['\ufeff'+csv(rs)],{type:'text/csv;charset=utf-8'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download='credit-file-'+name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000)}
function renderFund(){const rs=rows.filter(r=>String(r.bdcId)===state.fund&&r.period===state.period),ids=[...new Set(rs.map(r=>r.clientId))],scope=rs[0]?.scope;$('fundContent').innerHTML=`<p class="note">${esc(scope?.coverage||'No accepted rows for this quarter. Not evidence of zero exposure.')}</p><p>${ids.length} companies · ${rs.length} rows · Gross security FV ${short(completeSum(rs,'fairValue'))} · Reported net portfolio FV ${scope?.reconciliation?.reportedTotals?.fairValue != null ? money(Number(scope.reconciliation.reportedTotals.fairValue)) : 'Unavailable'} · Unallocated FV adjustments ${scope?.reconciliation?.unallocatedAdjustments ? money(scope.reconciliation.unallocatedAdjustments.filter(a=>a.field==='fairValue').reduce((s,a)=>s+Number(a.value),0)) : 'Unavailable'} (source-level adjustments; company marks unchanged). Partial accepted universe; no fund performance inference.</p><button id="exportFund">Export fund quarter CSV</button><div class="table-scroll" tabindex="0" role="region" aria-label="Fund companies"><table><thead><tr><th>Company</th><th>Security rows</th><th>Reported FV ($)</th></tr></thead><tbody>${ids.sort((a,b)=>companies[a].name.localeCompare(companies[b].name)).map(id=>{const cr=rs.filter(r=>r.clientId===id);return `<tr><td><button data-company="${id}">${esc(companies[id].name)}</button></td><td>${cr.length}</td><td class="num">${money(completeSum(cr,'fairValue'))}</td></tr>`}).join('')}</tbody></table></div>`;$('exportFund').onclick=()=>download(rs,'fund-'+state.period)}
function view(fund){$('companiesView').hidden=fund;$('fundsView').hidden=!fund;$('companiesNav').setAttribute('aria-pressed',String(!fund));$('fundsNav').setAttribute('aria-pressed',String(fund));if(fund)renderFund()}
$('periodSelect').innerHTML=[...new Set([...raw.periods,state.period])].sort().reverse().map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('');$('periodSelect').value=state.period;
$('periodSelect').onchange=e=>{state.period=e.target.value;updateURL();coverage();renderResults();renderProfile();if(!$('fundsView').hidden)renderFund()};
$('queryInput').oninput=e=>{state.query=e.target.value;state.limit=60;renderResults()};$('queryInput').onkeydown=e=>{if(e.key==='Enter'){const b=$('companyResults').querySelector('button');if(b)selectCompany(b.dataset.company,true)}};
$('currentOnly').onchange=e=>{state.currentOnly=e.target.checked;state.limit=60;renderResults()};$('resultSort').onchange=e=>{state.sort=e.target.value;renderResults()};
$('watchOnly').onchange=e=>{state.watchOnly=e.target.checked;renderResults()};$('multiOnly').onchange=e=>{state.multiOnly=e.target.checked;renderResults()};$('moreResults').onclick=()=>{state.limit+=60;renderResults()};
document.addEventListener('click',e=>{const jump=e.target.closest('[data-jump-movement]');if(jump){const targets=[...document.querySelectorAll('tr[data-movement]')].filter(r=>r.dataset.movement===jump.dataset.jumpMovement);document.querySelectorAll('.movement-evidence').forEach(r=>r.classList.remove('movement-evidence'));targets.forEach(r=>r.classList.add('movement-evidence'));if(targets[0]){targets[0].focus({preventScroll:true});targets[0].scrollIntoView({block:'center'});targets[0].closest('.table-scroll').scrollLeft=targets[0].scrollWidth;}}const b=e.target.closest('[data-company]');if(b){view(false);selectCompany(b.dataset.company,true)}});
$('companiesNav').onclick=()=>view(false);$('fundsNav').onclick=()=>view(true);$('fundSelect').innerHTML=raw.bdcs.map((b,i)=>`<option value="${i}">${esc(b.name)}</option>`).join('');$('fundSelect').onchange=e=>{state.fund=e.target.value;renderFund()};
// Read-only diagnostics expose the same pure financial functions consumed by the UI.
window.CreditFile={rows,ratio,completeSum,termsKey,identity,matchPrior,aggregateChange,csv,csvCell,groups,state};
storageNote();coverage();renderResults();renderProfile();window.BDC_DASHBOARD_READY=true;
})();
